### PR TITLE
Update gearmand-init.in

### PR DESCRIPTION
**Pull request by wd**
--verbose only support NOTICE, WARNGING etc. guess your guys forget to change it.

### CODE REVIEW

**Comment by sni** [comment]
Unfortunatly that depends on the gearmand version. I think i just remove that file from Mod-Gearman.

**Comment by wd** [comment]
Why remove that file? It's useful for Centos users..

**Comment by sni** [comment]
you could just use the gearmand pkg from the consol labs repository if you want.

**Comment by wd** [comment]
You mean download from here http://mod-gearman.org/download/v1.5.5/ ? There isn't a rhel5 pkg :( I have to build from source.

**Pull request closed without merging**
